#!/usr/bin/env python3
"""Generates the in-app string tables and legal texts (Kotlin) from:
  i18n/strings_zh.json, i18n/strings_en.json   -> app/src/main/java/net/zash/clashpanel/i18n/Strings.kt
  docs/privacy*.md, docs/agreement*.md         -> app/src/main/java/net/zash/clashpanel/i18n/LegalTexts.kt
Also checks that both tables have the same keys and that every t("key") used in the code exists.
Run after editing any of these files. Do not edit the generated files by hand."""
import json, os, re, sys
root = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
out_dir = os.path.join(root, 'app/src/main/java/net/zash/clashpanel/i18n')
os.makedirs(out_dir, exist_ok=True)


def kstr(s):
    return json.dumps(s, ensure_ascii=False).replace('$', '\\$')


zh = json.load(open(os.path.join(root, 'i18n/strings_zh.json'), encoding='utf-8'))
en = json.load(open(os.path.join(root, 'i18n/strings_en.json'), encoding='utf-8'))
diff = set(zh) ^ set(en)
if diff:
    sys.exit('key mismatch between zh/en: %s' % sorted(diff))

out = ['// Generated by scripts/gen-i18n.py from i18n/strings_*.json; do not edit by hand.',
       'package net.zash.clashpanel.i18n', '']
for name, d in (('ZH', zh), ('EN', en)):
    # HashMap filled in chunks keeps each JVM method small
    keys = sorted(d)
    out.append('internal val %s: HashMap<String, String> = HashMap<String, String>(%d).apply {' % (name, len(keys) * 2))
    chunks = [keys[i:i + 60] for i in range(0, len(keys), 60)]
    for i, _ in enumerate(chunks):
        out.append('    %s%d(this)' % (name.lower(), i))
    out.append('}')
    out.append('')
    for i, ch in enumerate(chunks):
        out.append('private fun %s%d(m: HashMap<String, String>) {' % (name.lower(), i))
        for k in ch:
            out.append('    m[%s] = %s' % (kstr(k), kstr(d[k])))
        out.append('}')
        out.append('')
open(os.path.join(out_dir, 'Strings.kt'), 'w', encoding='utf-8').write('\n'.join(out))


def lines(p):
    ls = open(os.path.join(root, p), encoding='utf-8').read().split('\n')
    while ls and ls[-1] == '':
        ls.pop()
    return ls


out = ['// Generated by scripts/gen-i18n.py from docs/*.md; do not edit by hand.', 'package net.zash.clashpanel.i18n', '']
for name, p in (('PRIVACY_ZH', 'docs/privacy.md'), ('AGREEMENT_ZH', 'docs/agreement.md'),
                ('PRIVACY_EN', 'docs/privacy_en.md'), ('AGREEMENT_EN', 'docs/agreement_en.md')):
    out.append('internal val %s: List<String> = listOf(' % name)
    out.append(',\n'.join('    ' + kstr(l) for l in lines(p)))
    out.append(')')
    out.append('')
open(os.path.join(out_dir, 'LegalTexts.kt'), 'w', encoding='utf-8').write('\n'.join(out))

# every t("...") key used in code must exist
src = os.path.join(root, 'app/src/main/java')
missing = set()
for dp, _, fs in os.walk(src):
    for f in fs:
        if f.endswith('.kt') and f not in ('Strings.kt', 'LegalTexts.kt'):
            for k in re.findall(r'\bt\("([a-z0-9_]+)"[,)]', open(os.path.join(dp, f), encoding='utf-8').read()):
                if k not in zh:
                    missing.add('%s: %s' % (f, k))
if missing:
    sys.exit('missing keys:\n  ' + '\n  '.join(sorted(missing)))
print('ok: %d keys' % len(zh))
